### ISSUE TITLE
Deprecated: What Now?

### ISSUE THREAD

**Issue by Blfrg** [projectcalico/canal#118]
I notice the repo is now deprecated, I have a few questions:

- Why has this been deprecated?
- What is the recommended path forward?

I thought at some point there was a goal to merge Calico and Flannel daemons into a single Canal daemon? Did this not prove beneficial?

- Should we just follow standard Calico guides?
- You linked to Canal instructions for v2.6 but the same category is not present in v3.0 docs.
-  v3.0 references this repo for Canal instructions
- Standard "Calico policy with Calico networking" is still listed as beta in v3.0

I really appreciate all your hard work and efforts and it saddens me to see this project deprecated.
I'm certain it's not without good reason.
I know the root Calico project is fully capable and don't mind reverting to it, but it seemed Canal would be the eventual preference.
Is the Flannel aspect no longer necessary?

**Comment by ozdanborne** [comment]
This _repo_ has been deprecated but the Canal project is alive and well - it's just being moved to the Calico docs repo so that it can be more easily released and stay up to date with Calico.

I think the deprecation message on this repo can be improved to better convey this, as right now it does sound like the project itself is deprecated.

**Comment by tmjd** [comment]
> Why has this been deprecated?

The repo has been deprecated, but not the Canal deployment method. This was done to have the docs and manifests as part of the main Calico docs instead of living separately.

>  What is the recommended path forward?

Canal will continue to be updated and is a viable installation method.

> I thought at some point there was a goal to merge Calico and Flannel daemons into a single Canal daemon? Did this not prove beneficial?

I'm not aware of a specific plan to merge the daemons/code bases together (that could have been before I was involved).

> Should we just follow standard Calico guides?

You can still use Canal, the manifests and directions will now be located in the Calico docs.

> You linked to Canal instructions for v2.6 but the same category is not present in v3.0 docs.

The instructions and manifests under v2.6 are more up to date than what was in the Canal repo, so it was not just a move but an update also. There will be an update for the v3.0 docs hopefully before too long but there was an issue that I found when deploying in the Canal configuration with Calico v3.0 (issue: https://github.com/projectcalico/calico/issues/1643) (the in progress updated docs for v3.0 https://github.com/projectcalico/calico/pull/1642, they're in the master directory but will be the same for v3.0).

> v3.0 references this repo for Canal instructions

Good point, those should be cleaned up.

> Standard "Calico policy with Calico networking" is still listed as beta in v3.0

True.  I'm not sure what is on the roadmap as far as when that will be out of beta, but there aren't many features left that it does not cover so hopefully not far off.

I've just put up https://github.com/projectcalico/canal/pull/119 to try to clarify the deprecation notice, feel free to comment there if you like.

Part of what this will help with is that the migration of Calico data from v2.6 to v3.0 requires some specific steps. As in upgrading to v2.6 and then from there installing v3.0.  This was difficult with Canal as it was just a repo with no 'releases', moving into the Calico docs was an easy way to have versioned releases of Canal. The move will also hopefully keep the Canal docs and manifests more in sync and updated with new Calico releases.

I hope this helps.

**Comment by Blfrg** [comment]
@ozdanborne & @tmjd Thank you for the clarification.

I'm sure this will help streamline project maintenance. Staying current over here did seem somewhat of an afterthought compared to the manifest updates seen for regular Calico.

However aside from the docs available on the front-end site it seems we'll have to scour deep into the Calico repo to find [Canal](https://github.com/projectcalico/calico/tree/master/v2.6/getting-started/kubernetes/installation/hosted/canal) (per version)
Which again, at present there's no v3.0 equivalent for Canal.

I'm still curious: is [or will] Canal offering a benefit over straight Calico?
If I'm able to get Calico running solo with it's provided manifests, would that be wholly sufficient, or is it lacking somehow compared to Canal? The separation of concerns with Calico [Policy]+Flannel is still appealing to me, but is the complexity necessary?

@tmjd's reply came in as I was typing this, I'll get current with the added details provided regarding Canal v3.0 issues. Thank you!

Note: The reference to a merged daemon appeared in the readme [here](https://github.com/projectcalico/canal/blob/e040917ea9c540ef1affe65a5227f2042be3fe7f/README.md) but has since disappeared, no biggie but it sounded helpful and simplified. Maybe it ultimately wasn't possible.

**Comment by tmjd** [comment]
One benefit of using Canal would be the ability to use the networking options that flannel provides, really that is the only benefit that I am aware of.

If you can run Calico and it meets your needs then I don't think there is any benefit of running canal/flannel.
